-- Generated by nwg-displays on 2026-09-06 at 18:09:54. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "2360x0",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "440x0",
    scale = 1,
    vrr = 0
})
