
[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0

decorations = "Buttonless"

opacity = 1
blur = false

option_as_alt = "Both"

[font]

[general]
import = [
	"/home/ruhanshafi/dotfiles/.config/alacritty/catppuccin-mocha.toml"
]
#normal.family = "MesloLGS Nerd Font Mono"

#size = 11
